# load common setting
source ~/dotfiles/zsh/common/zshrc

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# trash
alias rm="trash"

# neovim alias
alias vi="nvim"
alias vim="nvim"

# golang
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin

# nodebrew
export PATH=$PATH:$HOME/.nodebrew/current/bin

# ctags
alias ctags=/usr/local/Cellar/ctags/5.8_1/bin/ctags
