[[plugins]] # dein
repo = 'Shougo/dein.vim'

[[plugins]] # onedark-colorscheme
repo = 'joshdick/onedark.vim'

[[plugins]] # vim-commentary
repo = 'tpope/vim-commentary'

[[plugins]] # surround.vim
repo = 'tpope/vim-surround'

[[plugins]] # カッコ自動補完
repo = 'itmammoth/doorboy.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/dotfiles/nvim/rc/plugins/lightline.rc.vim
'''

[[plugins]] # 軽量ファイラ
repo = 'justinmk/vim-dirvish'
hook_add = '''
  source ~/dotfiles/nvim/rc/plugins/vim-dirvish.rc.vim
'''

[[plugins]] # sudoでもvimrcを共有
repo = 'vim-scripts/sudo.vim'
