[[plugins]] # 絞込系ファイラ
repo = 'ctrlpvim/ctrlp.vim'
on_map = '<C-p>'

[[plugins]] # カーソルの位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # deoplete
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]] # deoplete C/C++補完
repo = 'zchee/deoplete-clang'
on_ft = ['c','cpp']
depends = 'deoplete.nvim'
hook_source = '''
  source ~/dotfiles/nvim/rc/plugins/deoplete-clang.rc.vim
'''

[[plugins]] # deoplete node.js補完(tern)
repo = 'carlitux/deoplete-ternjs'
if = 'has("python3")'
on_ft = ['javascript','jsx','vue']
depends = 'deoplete.nvim'
hook_post_update = '''
  let cmd = 'npm install -g tern'
  let g:dein#plugin.build = cmd
'''
hook_source = '''
  source ~/dotfiles/nvim/rc/plugins/deoplete-ternjs.rc.vim
'''

[[plugins]] # シンタックスチェックフレームワーク
repo = 'neomake/neomake'
on_path = '.*'
hook_add = '''
    autocmd! BufWritePost * Neomake
'''
hook_source = '''
  source ~/dotfiles/nvim/rc/plugins/neomake.rc.vim
'''

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_source = '''
  set helplang=ja,en
'''

[[plugins]] # Codic
repo = 'koron/codic-vim'
on_cmd = 'Codic'

[[plugins]] # git操作
repo = 'tpope/vim-fugitive'
on_cmd = ['Gstatus','Gwrite','Gread','Gmove',
          'Gremoe','Gcommit','Gblame','Gdiff',
          'Glcd','Gcd','Git','Git!','Ggrep','Glog']

[[plugins]] # vim-gista
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
hook_source = '''
  let g:gista#client#default_username = 'd0n0'
'''

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_i = 1
hook_source = '''
  source ~/dotfiles/nvim/rc/plugins/emmet-vim.rc.vim
'''

[[plugins]]
repo = 'vimlab/split-term.vim'
on_cmd = ['Term','VTerm']
hook_source = '''
  set splitbelow
  set splitright
'''

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']
hook_source = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''

[[plugins]] # jsdoc
repo = 'heavenshell/vim-jsdoc'
on_ft = ['javascript']

[[plugins]] # javascript-syntaxhighlight
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]] # jsx syntaxhighlight
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript','jsx']

[[plugins]] # Go development plugin
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
  source ~/dotfiles/nvim/rc/plugins/vim-go.rc.vim
'''

[[plugins]] # smooth-scroll
repo = 'yuttie/comfortable-motion.vim'
on_map = ['<C-d>', '<C-u>', '<C-f>', '<C-b>']

# [[plugins]] # ローカルインストールしたESLintを使うためのプラグイン
# repo = 'benjie/neomake-local-eslint.vim'
# on_ft = ['javascript']
# on_cmd = ['EnableESLint']

# [[plugins]] # EditorConfig
# repo = 'editorconfig/editorconfig-vim'
# on_path = '.*'

# [[plugins]] # tmuxのステータスラインをプリセットを生成
# repo = 'edkolev/tmuxline.vim'
# on_cmd = 'Tmuxline'
# hook_source = '''
#   source ~/dotfiles/nvim/rc/plugins/tmuxline.rc.vim
# '''
